### PR TITLE
updated version numbers in composer json file

### PR DESCRIPTION
**Pull request by jotasprout**
Found new version numbers at each repo and updated them in the composer.json file. How do I "check the default config files if they are compatible with the updated packages"?

### CODE REVIEW

**Comment by daniel-werner** [comment]
Hey @jotasprout,
When installing the package it copies the `phpcs.xml` and `phpmd.xml` to the project. Please check if these config files are compatible with the new version of phpcs and phpmd you added. 
You can simply try to run both phpcs and phpmd commands in the package and check if they don't throw an error.

**Comment by jotasprout** [comment]
I apologize, I've been trying to look up how to do this -- I've never used Composer -- and I don't think I'm able to finish this task because of my ignorance.

**Comment by daniel-werner** [comment]
@jotasprout No worries, I'll still accept the PR, as it is useful. We'll finish the rest, no problem. Thanks

**Comment by jotasprout** [comment]
I'm trying to figure out how to start a new PHP project in Visual Studio but it won't let me install the PHP extensions. I am quite familiar with PHP I've just never used Composer and struggling to learn VS (VS Code I love). Thanks for accepting the PR -- I'm trying to learn and do as much as I can.

**Pull request merged**
