### PR TITLE
#2 Add missing docblock comments

### LINKED ISSUE #2: Add missing docblock comments
Add docblock comments where it is missing

### PR DESCRIPTION
**Pull request by krlv**
Hey @daniel-werner ! 

Fixes #2 Let me know if I fix all missing docs. 

Also, what do you think about `@return void`? I added them, but I know some people have a really strong opinion against them.

P.S.: interesting & helpful project. Would be really cool to see how it evolve! 👍

### CODE REVIEW

**Comment by daniel-werner** [comment]
Hey @krlv ,

Thanks for the PR, there is only 1 more function in `src/helpers.php`, with missing docblock. It would be greatly appreciated If you could add it.

**Comment by daniel-werner** [comment]
p.s. The return void is fine.

**Comment by krlv** [comment]
@daniel-werner sorry, missed that `guessSrcDirectory` helper. Fixed!

**Comment by daniel-werner** [comment]
@krlv Thanks, merging it!

**Pull request merged**
